language: node_js
node_js:
- '6'
- '10'
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: ZVHBq34gCJ5eI8v1sKCnVocH4vjs1ZUBSAB2rHHBQIK+pwBpOCaaO5Qxlzi4BW516HqM5Sc6g/ADG/tPyljIw3afjyXFZmBtA3eyWXSIUcdd6eu8ZsisqrKip3IfnsPL4lcB6fdrCCYeTe5S9r6ia8hdUVOznD5dBAl5fegSnQY=
  on:
    tags: true
    repo: noflo/noflo-google
